### ISSUE TITLE
Upload to littlefs does not show anymore on the Command Palette

### ISSUE THREAD

**Issue by miceno** [earlephilhower/arduino-littlefs-upload#48]
I was using the plugin on Arduino IDE, till a couple of days ago. 

Then, it stop showing on the Command Palette. I am not sure if I updated anything, but I am not aware of making any intentional change to the configuration.

I reinstalled it several times, but I didn't manage to make it show again.

Is there a way to get some logs about the reason it is not loading?

Details:
OS: MacOS 14.6.1 (23G93)
Hardware: M1 (arm)
Arduino IDE: 2.3.2
Board: NodeMCU flavours

**Comment by miceno** [comment]
I rebooted the computer and it was solved, it looks like there was some port or resource that was not properly freed, and the reboot released it.

**Comment by Hacking-Away** [comment]
Adding that I have this same issue, with the same resolution - a login/out cycle does not fix it, a reboot does.  Is there any logging or testing that would help track it down?

OS: MacOS 14.6.1 (23G93)
Hardware: M2 (arm)
Arduino IDE: 2.3.3
Board: Lolin D32

**Comment by earlephilhower** [comment]
This plugin has no state and doesn't control the command palette, so what you're seeing would be better tracked in the Arduino ide repo.  Might be an Apple and Electron interaction.
